---
format: 
   revealjs:
    embed-resources: true
    theme: serif
    toc: true
    toc-depth: 2
    toc-title: outline
    slide-level: 3
    slide-number: true
    show-slide-number: all
    preview-links: auto
    number-sections: true
    css: styles.css
    plugins:
      - menu
title: "Causal Inference and Experimentation"
subtitle: "Introduction to the class"
author: "Macartan Humphreys"
bibliography: bib.bib
include-before-body:
  text: |
    <script src="plugins/menu/menu.js"></script>
    <script>
      Reveal.initialize({
        plugins: [ RevealMenu ]
        menu: {
    // Specifies which side of the presentation the menu will
    // be shown. Use 'left' or 'right'.
    side: 'right'}
      });
    </script>
---


```{r, message = FALSE, echo = FALSE, include = FALSE}
source("setup.R")
run <- FALSE
```


## Getting started {#secoutline}

* General aims and structure
* Expectations
* Pointers for exercises
* Quick `DeclareDesign` intro

## Aims and items

* Deep understanding of key ideas in causal inference 
* Transportable tools for understanding how to evaluate and improve design
* Applied skills for design and analysis
* Exposure to open science practices
* Deeper dive into some specific topics (see survey)

### Syllabus and resources

* [https://macartan.github.io/ci](https://macartan.github.io/ci) for all resources
* [https://macartan.github.io/ci/syllabus.pdf](https://macartan.github.io/ci/syllabus.pdf)
* Git repo [https://github.com/macartan/ci](https://github.com/macartan/ci)
* [Student survey](https://cloud.wzb.eu/apps/forms/s/8QmokT5GeQfkmkrBHDzrzN4j): Please fill this out today.

### The topics {.smaller}

Day 1: Intro

* [1.1	Course outline, tools](#secoutline)
* [1.2	Introduction to `DeclareDesign`](#secdd)

Day 2: Causality

* [2.1	Fundamental problems and solutions](#seccausality)
* [2.2	Inquiries and identification](#secestimands) 

### The topics  {.smaller}

Day 3: Estimation and Inference

* [3.1	Frequentist](#secfisher)
* [3.2	Bayesian](#secbayes)

Day 4:

* [4.1	Experimental Design (esp. assignment)](#secdesign)
* [4.2	Design evaluation (esp. power)](#secdiagnosis)

Day 5: 

* [5.1	Topics and techniques](#citopics)
* [5.2	Open science](#openscience)


## Responsibilities

### Expectations {.smaller}

* 5 tasks
* (Required) Work in four "exercise teams": 1 team (and typically 2 exercises) per session $\times 4$ 
* (Optional) Prepare a research design or short paper, perhaps building on existing work. Typically this contains: 
  - a problem statement
  - a description of a method to address the problem
  - analytic or simulation based results describing properties of the solution
  - a discussion of implications for practice. 

A passing paper will illustrate subtle features of a method; a good paper will identify unknown properties of a method; en excellent paper will develop a new method. 

* Plus general reading and participation. 


### Exercise team job {.smaller}

Teams should prepare 15 - 20 minute presentations on set puzzles. Typically the task is to:

* Take a puzzle
* Declare and diagnose a design that shows the issue under study (e.g. some estimator produces unbiased estimates under some condition)
* Modify the design to show behavior when conditions are violated 

* Share a report with the class. Best in self-contained documents for easy third party viewing. e.g. `.html` via `.qmd` or `.Rmd`
* Presentations should be about 10 minutes for a given puzzle.

## Tips

### Good coding rules 

* [https://bookdown.org/content/d1e53ac9-28ce-472f-bc2c-f499f18264a3/code.html](https://bookdown.org/content/d1e53ac9-28ce-472f-bc2c-f499f18264a3/code.html)
* [https://www.r-bloggers.com/2018/09/r-code-best-practices/](https://www.r-bloggers.com/2018/09/r-code-best-practices/)

### Good coding rules   {.smaller}

* Metadata first
* Call packages at the beginning: use `pacman` 
* Put options at the top
* Call all data files once, at the top. Best to call directly from a public archive, when possible.  
* Use functions and define them at the top: comment them; useful sometimes to illustrate what they do
* Replicate first, re-analyze second. Use sections.
* (For replications) Have subsections named after specific tables, figures or analyses


### Aim


* First best: If someone has access to your `.Rmd`/`.qmd` file they can hit render or compile and the whole thing reproduces first time.  So:  Nothing local, everything relative: so please do not include hardcoded paths to your computer

*  But: often you need ancillary files for data and code. That's OK but aims should still be that with a self contained folder someone can open a `main.Rmd` file, hit compile and get everything. I usually have an `input` and an `output` subfolder.


### Collaborative coding / writing  {.smaller}

* Do not get in the business of passing attachments around
* Documents in some cloud: `git`, osf, Dropbox, Drive, Nextcloud
* General rule: only post non sensitive, non proprietary material
* Share self contained folders; folders contain a small set of live documents plus an archive. Old versions of documents are in archive. Only one version of the most recent document is in a main folder.
* Data is self contained folder (`in`) and is never edited directly
* Update to github frequently


