---
title: "PH_5.4"
format:
  revealjs: 
    theme: white
    logo: hu_siegel-kombi_rgb.png
    css: logo.css
    mbed-resources: true
    slide-level: 3
    slide-number: true
    show-slide-number: all
    preview-links: auto
    number-sections: false
    scrollable: true
    chalkboard: true
---

```{r include=FALSE}
p_needed <- c(
  "knitr",
  "tidyverse",
  "CausalQueries",
  "DeclareDesign",
  "ggdag",
  "ggplot2",
  "dagitty",
  "rstan"
)

# check if packages are installed and if not, install them
lapply(p_needed[!(p_needed %in% rownames(installed.packages()))], install.packages)

# prepare packages for use with library
lapply(p_needed, library, character.only = TRUE)
```

```{r}
set.seed(84756)
```

```{r}
model_64 <- '
data {
  vector[400] Y;
  int<lower=0,upper=1> X[400];
  int school[400];
}
parameters {
  vector<lower=0>[3] sigma; 
  vector[20] a;
  vector[20] b;
  real mu_a;
  real mu_b;
}
transformed parameters {
  vector[400] Y_sx;
  for (i in 1:400) Y_sx[i] = a[school[i]] + b[school[i]] * X[i];
}
model {
  a ~ normal(mu_a, sigma[1]);
  b ~ normal(mu_b, sigma[2]);
  Y ~ normal(Y_sx, sigma[3]);
}
'

school   <- rep(1:20, each = 20)
school_b <- 1 + rnorm(20)
X         <- rep(0:1, 200)
Y         <- school_b[school]*X + rnorm(400)

data_64 <- list(
  school = school,
  X = X, 
  Y = Y)

M_64 <- stan(model_code = model_64, data = data_64)
```

```{r}
print(M_64, pars = c("sigma[1]", "sigma[2]", "sigma[3]", "mu_a", "mu_b"))
```


