---
format: 
   revealjs:
    embed-resources: true
    theme: serif
    slide-level: 3
    slide-number: true
    show-slide-number: all
    preview-links: auto
    number-sections: false
    code-fold: show
    code-summary: "Show the code"
    scrollable: true
    echo: true
title: "Exercise 7.2"
author: "Eduard, Felix, Linus & Noah"
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, echo=FALSE}
# install and load packages
if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  DeclareDesign,
  ri2,
  tidyverse,
  here,
  kableExtra
)

```

## Puzzle

**Heterogeneous propensities**

Two of four units are going to be assigned to treatment. A researcher sets up a design in which subjects can decide for themselves the probability with which they receive a treatment. Requested propensities are as below.

Can you :

1.  List the set of admissible treatment allocations
2.  Describe a scheme for allocating subjects to treatment
3.  Calculate your estimate under each allocation
4.  Assess whether your estimate will be biased or not.

## Puzzle (2)

| Requested propensity | Y0  | Y1  |
|----------------------|-----|-----|
| 0.2                  | 0   | 1   |
| 0.4                  | 0   | 2   |
| 0.6                  | 1   | 3   |
| 0.8                  | 1   | 4   |

# Solution

## Individual Treatment Effect

| Subject | Y0  | Y1  | T.E. |
|---------|-----|-----|------|
| A       | 0   | 1   | 1    |
| B       | 0   | 2   | 2    |
| C       | 1   | 3   | 2    |
| D       | 1   | 4   | 3    |

The real ATE is 2.

## Admissible treatment allocations

There are 6 possible treatment allocations:

1.  A and B

2.  A and C

3.  A and D

4.  B and C

5.  B and D

6.  C and D.

## Estimate under each allocation

| Allocation | ATE Estimate |
|------------|--------------|
| A and B    | 0.5          |
| A and C    | 1.5          |
| A and D    | 2            |
| B and C    | 2            |
| B and D    | 2.5          |
| C and D    | 3.5          |

## An allocation scheme

P(A) = 0.2, P(B) = 0.4, P(C) = 0.6, P(D) = 0.8

But each can be written as a sum, f.e.

P(A) = P(A and B) + P(A and C) + P(A and D)

Start with P(A and B) = 0.1 and P(A and C) = 0.05 and then calculate the probabilities for the other allocations

## An allocation scheme (2)

| Allocation | ATE Estimate | Probability |
|------------|--------------|-------------|
| A and B    | 0.5          | 0.1         |
| A and C    | 1.5          | 0.05        |
| A and D    | 2            | 0.05        |
| B and C    | 2            | 0.05        |
| B and D    | 2.5          | 0.25        |
| C and D    | 3.5          | 0.5         |

## Expected estimate and bias

The expected estimate is $$\sum_{i = 1}^6 ATE_i*p_i = 2.7$$
