---
title: "Group 1 - Week 4"
subtitle: "7 Experimental Design"
date: "1 Feburary, 2024"
date-format: "long"
author: Ziyu, Nora, Elias, Felix, Anton 
mbed-resources: true
slide-level: 3
slide-number: true
show-slide-number: all
preview-links: auto
number-sections: false
scrollable: true
chalkboard: true
---

  
```{r packages, echo=FALSE}
# packages
pacman::p_load(tidyverse,
               rstan,
               DeclareDesign,
               dagitty,
               CausalQueries,
               ri2,
               knitr,
               kableExtra)
```


 
# excercise 7.1
  ## Randomization
# DAG
## F: facilitators(treatment), G: Gender(Confounder?), Y: Social Trust(Outcome)
```{r}
dagitty("dag {F -> Y G ->Y}") %>%
  plot()
```





------------------Question 1------------------- 
  ##1. Sampling
  ###*100 students* sign up to take part in an experiment. 
  ###Half your subjects are men and half are women and you believe gender is very predictive of social trust.

```{r}
set.seed(123) #set seed for reproducibility
n <- 100 ##100 Students
g <- sample(c("male", "female"), n, replace = TRUE, prob = c(0.5, 0.5)) ##gender

##alternative
g1<-50
g0<-50


```

  ##2.Model&Inquiry
  ###You want to measure the effect of immigration on social trust. 

  ##3. Data Strategy
  ###Your experiment involves varying whether a “native” or an “immigrant” facilitator instructs players in how to play a trust game. 
  ###You have five native and five immigrant facilitators and you want them each to conduct one session with 10 subjects.
  ###You are free to assign both subjects and facilitators to sessions. 

```{r}
s <- 10 ##sessions: Facilitators
t <- sample(c("native", "immigrant"), s, replace = TRUE, prob = c(0.5, 0.5))  ## as we know, 5 are Native, 5 are Immigrant

```

#Question 1:
##Propose an appropriate randomization strategy.
##Is it blocked? Clustered? Both?
# Yes, it is block, because in this case, as the gender is clear a character, we should use the stratified randomization,
```{r}
## using striated random assignment on gender 
random1 <- declare_assignment(strata_rs(strata = g))
``` 

# but it could be clustered, as the people stay in the same facilitator are not go into the sample together. 
```{r}
##possibility 1: put in same session together(cluster)
treatment_session_assignments <- block_ra(blocks = rep(1:t, each = 5),
                                          conditions = "native",
                                          clusters = female)

control_session_assignments <- block_ra(blocks = rep(1:t, each = 5),
                                        conditions = "immigrant",
                                        clusters = female)

##possibility 2: don't put in the same session(non-clustered)



```  
#Answer1: It is blocked, as we assigned in each block(facilitator) specific number of female and male students, to root out the potential influence from the gender dynamic. 
```{r}
design <- 
  declare_model(N=n,
                G=g,
                F=rnorm(n, 0, 1), ##??
                Y=) +             ##??
  declare_inquiry(ATE=mean(Y_F_1-Y_F_0)) +##effect of facilitator/immigration
  declare_potential_outcomes(Y~F)+
  declare_sampling()
  declare_assignment(F=block_ra(block = G, block_prob = c(0.5, 0.5)))+##using 'gender' as block and assign them to facilitator
  declare_measurement(Y= reveal_outcomes(Y~F))
```

-----------------------------------------------
------------------Question 2-------------------
#Question2: Say now that subjects have already signed up for sessions. 
##You can only assign facilitators to sessions, 
# that mean complete sampling at the first
```{r}
random2 <- declare_assignment(complete_ra(N))
```  
##but you have access to the subject lists before you do so. 
# that means there is a bias due to the knowledge about gender bias.
##Describe your optimal randomization strategy.
# the strategy is random assignment: there are 10 session to 2 possibilities, but each possibility has only 5 times. Means, treatment has 5 times, control has 5 times. 
##Is it blocked? Clustered? Both?
# Thus, it is cluster, because the sessions are put into treatment sample together, the other 5 session are put into control sample together. 
# But it is not blocked, because each session haven't considered the gender problem, although you know the number of gender difference in each session 
# it might be solve by sim 
```{r}
N<-100
S<-10 ##10sessions
assignments <- sample(1:S, N, replace = TRUE)
treatment_sessions <- sample(unique(assignments), S/2) ##make sure 5 in treatment 
control_sessions <- setdiff(1:S, treatment_sessions) 
group_assignment <- ifelse(assignments %in% treatment_sessions, 1, 0) ## make sure other 5 in control
```

```{r}
m2 <- declare_model()

```  





-----------------------------------------------
  