---
format: 
   revealjs:
    embed-resources: true
    theme: serif
    slide-level: 3
    slide-number: true
    show-slide-number: all
    preview-links: auto
    number-sections: true
title: "Topics"
subtitle: "workflows: finding questions"
author: "Macartan Humphreys"
bibliography: ../bib.bib
---

  
```{r, include = FALSE}
if(!exists("child")) setwd("../")

source("setup.R")

```



## Experimentation: Questions {#qs}

*Good questions studied well*


### When to experiment {#L_prospects}

Prospects and priorities

### Prospects 

* Whenever someone is uncertain about *something* they are doing (all the time)
* Whenever someone hits scarcity constraints
* When people have incentives to demonstrate that they are doing the right thing (careful...)

### Prospects 

* **Advice**: If you can, **start from theory** and find an intervention, rather than the other way around.
* **Advice**: If you can, go for *structure* rather than *gimmicks*
* **Advice**: In attempts to parse, beware of generating unnatural interventions (how should a voter think of a politician that describes his policy towards Korea in detail but does not mention the economy? Is not mentioning the economy sending an unintended message?)

### Innovative designs {.smaller}

* Randomization of where police are stationed (India)
* Randomization of how government tax collectors get paid (do they get a share?) (Pakistan)
* Randomization of the voting rules for determining how decisions get made (Afghanistan)
* Random assignment of populations to peacekeepers (Liberia)
* Random assignment of ex-combatants out of their networks (Indonesia)
* Randomization of students to ethnically homogeneous or ethnically diverse schools (anywhere?)


